preview = true
line-length = 99

[format]
preview = true
skip-magic-trailing-comma = true
docstring-code-format = true

[lint]
ignore = [
  "RUF003",
  "PERF203",
  "RUF012",
  "ANN",  
  "E722",
]
select = [
  "F",
  "G",    
  "PERF", 
  "RUF",  
  "W6",
  "E71",
  "E72",
  "E112",
  "E113",
  "E272",
  "E203",
  "E702",
  "E703",
  "E731",
  "W191",
  "W291",
  "W293",
  "UP039", 
]

[lint.pydocstyle]
convention = "google"