# General settings
# ----------------------------------------------------------------
offset:
  offset: false
  value: 2 # min 2 : max 250

release_date:
  release_date: false
  years:
  -

titles: # example: steam; cat
-

# LP-Parser settings
# ----------------------------------------------------------------
exceptions:
-

# DON'T TOUCH IF YOU DON'T WHAT ARE YOU DOING
for_advanced_users:
  login_regex: \S+@\S+\.\S+ # All logins are a email
  password_regex: \S*\d\S* # All words that contain a digit are considered a password
