name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tuparser
    permissions:
      id-token: write  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # - name: Setup Python 3.12
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: 3.12
    - name: Build package
      run: |
        python -m pip install -r dev_requirements.txt
        python -m pip install -r requirements.txt
        python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
